require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LeagueusersController do

  # This should return the minimal set of attributes required to create a valid
  # Leagueuser. As you add validations to Leagueuser, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LeagueusersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all leagueusers as @leagueusers" do
      leagueuser = Leagueuser.create! valid_attributes
      get :index, {}, valid_session
      assigns(:leagueusers).should eq([leagueuser])
    end
  end

  describe "GET show" do
    it "assigns the requested leagueuser as @leagueuser" do
      leagueuser = Leagueuser.create! valid_attributes
      get :show, {:id => leagueuser.to_param}, valid_session
      assigns(:leagueuser).should eq(leagueuser)
    end
  end

  describe "GET new" do
    it "assigns a new leagueuser as @leagueuser" do
      get :new, {}, valid_session
      assigns(:leagueuser).should be_a_new(Leagueuser)
    end
  end

  describe "GET edit" do
    it "assigns the requested leagueuser as @leagueuser" do
      leagueuser = Leagueuser.create! valid_attributes
      get :edit, {:id => leagueuser.to_param}, valid_session
      assigns(:leagueuser).should eq(leagueuser)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Leagueuser" do
        expect {
          post :create, {:leagueuser => valid_attributes}, valid_session
        }.to change(Leagueuser, :count).by(1)
      end

      it "assigns a newly created leagueuser as @leagueuser" do
        post :create, {:leagueuser => valid_attributes}, valid_session
        assigns(:leagueuser).should be_a(Leagueuser)
        assigns(:leagueuser).should be_persisted
      end

      it "redirects to the created leagueuser" do
        post :create, {:leagueuser => valid_attributes}, valid_session
        response.should redirect_to(Leagueuser.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved leagueuser as @leagueuser" do
        # Trigger the behavior that occurs when invalid params are submitted
        Leagueuser.any_instance.stub(:save).and_return(false)
        post :create, {:leagueuser => {}}, valid_session
        assigns(:leagueuser).should be_a_new(Leagueuser)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Leagueuser.any_instance.stub(:save).and_return(false)
        post :create, {:leagueuser => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested leagueuser" do
        leagueuser = Leagueuser.create! valid_attributes
        # Assuming there are no other leagueusers in the database, this
        # specifies that the Leagueuser created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Leagueuser.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => leagueuser.to_param, :leagueuser => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested leagueuser as @leagueuser" do
        leagueuser = Leagueuser.create! valid_attributes
        put :update, {:id => leagueuser.to_param, :leagueuser => valid_attributes}, valid_session
        assigns(:leagueuser).should eq(leagueuser)
      end

      it "redirects to the leagueuser" do
        leagueuser = Leagueuser.create! valid_attributes
        put :update, {:id => leagueuser.to_param, :leagueuser => valid_attributes}, valid_session
        response.should redirect_to(leagueuser)
      end
    end

    describe "with invalid params" do
      it "assigns the leagueuser as @leagueuser" do
        leagueuser = Leagueuser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Leagueuser.any_instance.stub(:save).and_return(false)
        put :update, {:id => leagueuser.to_param, :leagueuser => {}}, valid_session
        assigns(:leagueuser).should eq(leagueuser)
      end

      it "re-renders the 'edit' template" do
        leagueuser = Leagueuser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Leagueuser.any_instance.stub(:save).and_return(false)
        put :update, {:id => leagueuser.to_param, :leagueuser => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested leagueuser" do
      leagueuser = Leagueuser.create! valid_attributes
      expect {
        delete :destroy, {:id => leagueuser.to_param}, valid_session
      }.to change(Leagueuser, :count).by(-1)
    end

    it "redirects to the leagueusers list" do
      leagueuser = Leagueuser.create! valid_attributes
      delete :destroy, {:id => leagueuser.to_param}, valid_session
      response.should redirect_to(leagueusers_url)
    end
  end

end
