require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TrackusersController do

  # This should return the minimal set of attributes required to create a valid
  # Trackuser. As you add validations to Trackuser, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TrackusersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all trackusers as @trackusers" do
      trackuser = Trackuser.create! valid_attributes
      get :index, {}, valid_session
      assigns(:trackusers).should eq([trackuser])
    end
  end

  describe "GET show" do
    it "assigns the requested trackuser as @trackuser" do
      trackuser = Trackuser.create! valid_attributes
      get :show, {:id => trackuser.to_param}, valid_session
      assigns(:trackuser).should eq(trackuser)
    end
  end

  describe "GET new" do
    it "assigns a new trackuser as @trackuser" do
      get :new, {}, valid_session
      assigns(:trackuser).should be_a_new(Trackuser)
    end
  end

  describe "GET edit" do
    it "assigns the requested trackuser as @trackuser" do
      trackuser = Trackuser.create! valid_attributes
      get :edit, {:id => trackuser.to_param}, valid_session
      assigns(:trackuser).should eq(trackuser)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Trackuser" do
        expect {
          post :create, {:trackuser => valid_attributes}, valid_session
        }.to change(Trackuser, :count).by(1)
      end

      it "assigns a newly created trackuser as @trackuser" do
        post :create, {:trackuser => valid_attributes}, valid_session
        assigns(:trackuser).should be_a(Trackuser)
        assigns(:trackuser).should be_persisted
      end

      it "redirects to the created trackuser" do
        post :create, {:trackuser => valid_attributes}, valid_session
        response.should redirect_to(Trackuser.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved trackuser as @trackuser" do
        # Trigger the behavior that occurs when invalid params are submitted
        Trackuser.any_instance.stub(:save).and_return(false)
        post :create, {:trackuser => {}}, valid_session
        assigns(:trackuser).should be_a_new(Trackuser)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Trackuser.any_instance.stub(:save).and_return(false)
        post :create, {:trackuser => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested trackuser" do
        trackuser = Trackuser.create! valid_attributes
        # Assuming there are no other trackusers in the database, this
        # specifies that the Trackuser created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Trackuser.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => trackuser.to_param, :trackuser => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested trackuser as @trackuser" do
        trackuser = Trackuser.create! valid_attributes
        put :update, {:id => trackuser.to_param, :trackuser => valid_attributes}, valid_session
        assigns(:trackuser).should eq(trackuser)
      end

      it "redirects to the trackuser" do
        trackuser = Trackuser.create! valid_attributes
        put :update, {:id => trackuser.to_param, :trackuser => valid_attributes}, valid_session
        response.should redirect_to(trackuser)
      end
    end

    describe "with invalid params" do
      it "assigns the trackuser as @trackuser" do
        trackuser = Trackuser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Trackuser.any_instance.stub(:save).and_return(false)
        put :update, {:id => trackuser.to_param, :trackuser => {}}, valid_session
        assigns(:trackuser).should eq(trackuser)
      end

      it "re-renders the 'edit' template" do
        trackuser = Trackuser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Trackuser.any_instance.stub(:save).and_return(false)
        put :update, {:id => trackuser.to_param, :trackuser => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested trackuser" do
      trackuser = Trackuser.create! valid_attributes
      expect {
        delete :destroy, {:id => trackuser.to_param}, valid_session
      }.to change(Trackuser, :count).by(-1)
    end

    it "redirects to the trackusers list" do
      trackuser = Trackuser.create! valid_attributes
      delete :destroy, {:id => trackuser.to_param}, valid_session
      response.should redirect_to(trackusers_url)
    end
  end

end
